exception A;

def main() {
    try {
        raise A;
    } except B {
        print(1);
    }
    return;
}
